"""Add user authentication tables

Revision ID: 3168533453e2
Revises: 77c4264bb431
Create Date: 2025-08-21 23:11:07.442350

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3168533453e2'
down_revision: Union[str, Sequence[str], None] = '77c4264bb431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('email_verification_expires', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('analysis_count', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    # Add columns as nullable first
    op.add_column('analyses', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('analyses', sa.Column('full_text', sa.Text(), nullable=True))
    
    # Add columns to files as nullable first
    op.add_column('files', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('files', sa.Column('file_path', sa.String(length=500), nullable=True))
    
    # Create a default user for existing data
    default_user_id = str(uuid.uuid4())
    op.execute(f"""
        INSERT INTO users (id, email, password_hash, first_name, last_name, email_verified, is_active, is_premium, analysis_count, created_at, updated_at)
        VALUES ('{default_user_id}', 'default@noteguard.com', 'default_hash', 'Default', 'User', 1, 1, 0, 0, datetime('now'), datetime('now'))
    """)
    
    # Update existing analyses with default user and full_text
    op.execute(f"""
        UPDATE analyses 
        SET user_id = '{default_user_id}', 
            full_text = COALESCE(text_excerpt, 'Default text content')
        WHERE user_id IS NULL
    """)
    
    # Update existing files with default user and file_path
    op.execute(f"""
        UPDATE files 
        SET user_id = '{default_user_id}', 
            file_path = COALESCE(filename, 'default_file.txt')
        WHERE user_id IS NULL
    """)
    
    # Now make columns NOT NULL
    op.alter_column('analyses', 'user_id', nullable=False)
    op.alter_column('analyses', 'full_text', nullable=False)
    op.alter_column('files', 'user_id', nullable=False)
    op.alter_column('files', 'file_path', nullable=False)
    
    # Create foreign keys
    op.create_foreign_key(None, 'analyses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'files', 'analyses', ['analysis_id'], ['id'])
    op.create_foreign_key(None, 'files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'file_path')
    op.drop_column('files', 'user_id')
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.drop_column('analyses', 'full_text')
    op.drop_column('analyses', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
