"""initial schema

Revision ID: 5240790c327b
Revises: 
Create Date: 2025-08-12 16:33:18.525436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5240790c327b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=10), nullable=False),
    sa.Column('text_excerpt', sa.Text(), nullable=False),
    sa.Column('reference_topic', sa.String(length=200), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('grammar_score', sa.Float(), nullable=False),
    sa.Column('repetition_score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('grammar_errors', sa.JSON(), nullable=True),
    sa.Column('repetition_errors', sa.JSON(), nullable=True),
    sa.Column('semantic_coherence', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Float(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.drop_table('analyses')
    # ### end Alembic commands ###
