"""add_audit_fields

Revision ID: 77c4264bb431
Revises: performance_indexes
Create Date: 2025-08-21 17:26:49.060197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c4264bb431'
down_revision: Union[str, Sequence[str], None] = 'performance_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('request_id', sa.String(length=50), nullable=True))
    op.add_column('analyses', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.add_column('analyses', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_overall_score'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_source_type_created_at'), table_name='analyses')
    op.drop_index(op.f('ix_files_created_at'), table_name='files')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_files_created_at'), 'files', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyses_source_type_created_at'), 'analyses', ['source_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_analyses_overall_score'), 'analyses', ['overall_score'], unique=False)
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.drop_column('analyses', 'ip_address')
    op.drop_column('analyses', 'user_agent')
    op.drop_column('analyses', 'request_id')
    # ### end Alembic commands ###
